# Default configuration for KubeTracer
server:
  port: 8080
  host: "0.0.0.0"
  read_timeout: "10s"
  write_timeout: "10s"

scanner:
  interval: "5m"  # Scan interval
  workers: 3      # Number of worker goroutines

logging:
  level: "info"   # trace, debug, info, warn, error, fatal, panic
  format: "json"  # json or text

metrics:
  enabled: true
  port: 9090
